### PR TITLE
More Services!

### PR DESCRIPTION
**Pull request by ghost**
I added the following services: Netlify, Netdata, cdnjs, Geschafft, Epic Games, Twitter API

### CODE REVIEW

**Comment by alisalahio** [comment]
Hi @GhostSlayer,

Thank you so much for adding these! 
Would you please remove Geschafft from the pull request though?
I love that you're using Instatus, but I feel like we can't get away with this :D

**Comment by ghost** [comment]
I will remove Geschafft, but is there a reason why i'll need to remove it?

**Comment by alisalahio** [comment]
When I search for it on Google, it doesn't show up, so I have a feeling it's not popular yet :D

**Comment by ghost** [comment]
Oh okay!

**Comment by Aesth3tical** [comment]
> I will remove Geschafft, but is there a reason why i'll need to remove it?

Not really, it can be found on google as you can see below, and has around 1k users as of now. Idk what this other guy is talking about, but as a staff member there I can confirm this
Screenshot 2021-02-21 at 1 21 11 PM

**Comment by sinjs** [comment]
And this is why you shouldn't name a company a german word.

**Comment by ghost** [comment]
Its a dead hosting anyways so it doesn't matter if its added or not 😃 👍

**Comment by sinjs** [comment]
lmao

**Pull request merged**
