### PR TITLE
Add Supabase

### PR DESCRIPTION
**Pull request by andreivreja**

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank youu!! 🚀

**Comment by andreivreja** [comment]
No, thank YOU! Can we add personal projects that most people don't care about 👀? Would be nice not having to run my own fork.

**Comment by alisalahio** [comment]
I don't wanna allow it honestly, it can get crazy with time. 
Some people would add their projects just for marketing, so it gonna be a mess :D

**Comment by andreivreja** [comment]
Makes sense haha. Thanks for the merge, and for the amazing product you're building!

**Pull request merged**
