### PR TITLE
Add Deno

### PR DESCRIPTION
**Pull request by windchime-yk**
Added support for [Deno](https://denostatus.com/)

### CODE REVIEW

**Comment by alisalahio** [comment]
Thank you!!
Would you import it to our list of services?
https://github.com/instatushq/out/blob/main/src/services/index.ts

**Comment by windchime-yk** [comment]
@alisalahio 
Thank you for review!!
I’m added it.

**Comment by alisalahio** [comment]
LET'S GOOOOO

**Comment by windchime-yk** [comment]
@alisalahio 
Thank you for merge!
When do you plan to release it?

**Pull request merged**
